export const instrumentNames = [
  "-",
  "Drums",
  "Djembe",
  "Electric Guitar",
  "Acoustic Guitar",
  "Bass Guitar",
  "Keyboard",
  "Synthesizer",
  "Grand Piano",
  "Accordion",
  "Vocal",
  "Microphone",
  "Harmonica",
  "Trumpet",
  "Trombone",
  "French Horn",
  "Tuba",
  "Saxophone",
  "Clarinet",
  "Flute",
  "Violin",
  "Cello",
  "Double Bass",
  "Recorder",
  "Streamer",
  "Listener",
  "Guitar Vocal",
  "Keyboard Vocal",
  "Bodhran",
  "Bassoon",
  "Oboe",
  "Harp",
  "Viola",
  "Congas",
  "Bongo",
  "Vocal Bass",
  "Vocal Tenor",
  "Vocal Alto",
  "Vocal Soprano",
  "Banjo",
  "Mandolin",
  "Ukulele",
  "Bass Ukulele",
  "Vocal Baritone",
  "Vocal Lead",
  "Mountain Dulcimer",
  "Scratching",
  "Rapping",
  "Vibraphone",
  "Conductor",
];
